sudo: required
dist: trusty
language: java
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
jdk:
  - oraclejdk8

os:
  - linux
  
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb

node_js:
  - 8
  - 6
  
script:
  - npm install pm2 -g
  - npm run test
  - npm run prod
  - npm run serve
  - npm run featuretest

notifications:
  email:
    on_failure: change

cache:
  yarn: true
  directories:
    - node_modules
