language: node_js

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
jdk:
  - oraclejdk8

os:
  - linux

node_js:
  - 8
  - 6
  
script:
  - npm install pm2 -g
  - npm run test
  - npm run prod
  - npm run serve
  - npm run featuretest

notifications:
  email:
    on_failure: change

cache:
  yarn: true
  directories:
    - node_modules
